apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm
  namespace: {{ .Release.Namespace | default .Release.Name }}
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  docker.yaml: ''
  settings.yaml: |
    {{ toYaml .Values.settings | nindent 4 | trim }}
  bookmarks.yaml: |
    - Bookmarks:
    {{ toYaml .Values.bookmarks | nindent 6 }}
  services.yaml: |
    {{ toYaml .Values.services | nindent 4 | trim }}
  widgets.yaml: |
    {{ toYaml .Values.widgets | nindent 4 | trim }}
  custom_css: |
    {{ toYaml .Values.custom_css | nindent 4 | trim }}
  custom_js: |
    {{ toYaml .Values.custom_js | nindent 4 | trim }}