apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ .Release.Name }}-sa-token
  namespace: {{ .Release.Namespace | default .Release.Name }}
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    kubernetes.io/service-account.name: {{ .Release.Name }}-sa