apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sa
  namespace: {{ .Release.Namespace | default .Release.Name }}
  labels:
    app.kubernetes.io/name: homepage
secrets:
  - name: {{ .Release.Name }}-sa-token