name: Helm Release

on:
  push:
    branches:
      - main
      - master

jobs:
  helm-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Dependencies update
        run: helm dependency update ./chart

      - name: Lint
        run: helm lint ./chart

      - name: Package Helm chart
        run: helm package . -d .deploy

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: .
          config: cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"