name: Helm Release

on:
  push:
    branches:
      - main
    tags:
      - '*.*.*'
      - 'chart-*'

jobs:
  helm-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: List chart directory contents
        run: ls -R ./chart
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: .
          charts_url: https://jjghali.github.io/homepage-helm
          target_dir: ./charts
          owner: jjghali
          repository: homepage-helm
          branch: gh-pages